############################################## Parameter recovery
recov_res_true_m <- matrix(NA,nrow=PP,ncol=17)

recov_res_true_m[,1] <- rep(in_block_tr, PP)
recov_res_true_m[,2] <- rep(out_block_tr, PP)
recov_res_true_m[,3] <- rep(dr_sigma_tr, PP)
recov_res_true_m[,4] <- rep(dr_rho_tr, PP)
recov_res_true_m[,5] <- rep(sr_sigma_tr[1], PP)
recov_res_true_m[,6] <- rep(sr_sigma_tr[2], PP)
recov_res_true_m[,7] <- rep(sr_rho_tr, PP)
recov_res_true_m[,8]  <- rep(false_positive_rate_tr[1],PP)
recov_res_true_m[,9]  <- rep(false_positive_rate_tr[2],PP)
recov_res_true_m[,10] <- rep(recall_of_true_ties_tr[1], PP)
recov_res_true_m[,11] <- rep(recall_of_true_ties_tr[2], PP)
recov_res_true_m[,12] <- rep(fpr_sigma_tr[1], PP)
recov_res_true_m[,13] <- rep(fpr_sigma_tr[2], PP)
recov_res_true_m[,14] <- rep(rtt_sigma_tr[1], PP)
recov_res_true_m[,15] <- rep(rtt_sigma_tr[2], PP)
recov_res_true_m[,16] <- TR_test
recov_res_true_m[,17] <- rep(theta_sigma_tr, PP)

parameter_recovery_points_plots(PP, stanfit_tr, TR_test, recov_res_true_m, "TR")
parameter_recovery_corrs_plots(PP, stanfit_tr, TR_test, G_list, "TR")
parameter_recovery_MI_plots(PP, stanfit_tr, TR_test, G_list, "TR")
network_level_characters_plots(PP, stanfit_tr, TR_test,  G_list, "TR")
individual_level_characters_plots(PP, stanfit_tr, TR_test,  G_list, "TR")
individual_level_MI_characters_plots(PP, stanfit_tr, TR_test,  G_list, "TR")
